- name: "Configuring Namenode"
  hosts: NameNode
  vars:
    dir: /hadoop_NN
    node: name
    ip: 192.168.99.129
    hadoop_port: 9001
  tasks:
    - name: "Copy Installing file"
      copy:
        src: "{{ item }}"
        dest: "/root"
      loop:
        - "hadoop-1.2.1-1.x86_64.rpm"
        - "jdk-8u171-linux-x64.rpm"
                 
    - name: "Installing Java"
      package:
        name: "jdk-8u171-linux-x64.rpm"
        state: present
    - name: "Checking hadoop and installing"
      block:
        - name: "Checking hadoop"
          command: "rpm -q hadoop"
          changed_when: False
      rescue:
        - name: "Installing hadoop"
          command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
    - name: "Configuring Hadoop Namenode"
      template:
        src: "{{ item }}"
        dest: "/etc/hadoop"
      loop:
        - "hdfs-site.xml"
        - "core-site.xml"
      notify:
        - "Creating Namenode Directory"
        - "Format hadoop dir"
        - "start hadoop"
    - name: Enable Firewall to port 9001
      firewalld:
        port: "9001/tcp"
        state: enabled
        permanent: yes
        immediate: yes
  handlers:
    - name: "Creating Namenode Directory"
      file:
        path: "{{ dir }}"
        state: "directory"
    - name : "Format hadoop dir"
      command: "hadoop namenode -format"
      args:
        stdin: "Y"
    - name: "start hadoop"
      command: "hadoop-daemon.sh start namenode"

- name: "Configuring Datanode"
  hosts: DataNode 
  vars:
    dir: /hadoop_DN
    node: data
    ip: 192.168.99.129
    hadoop_port: 9001
  tasks:
    - name: "Copy Installing file"
      copy:
        src: "{{ item }}"
        dest: "/root"
      loop:
        - "hadoop-1.2.1-1.x86_64.rpm"
        - "jdk-8u171-linux-x64.rpm"
    - name: "Installing Java"
      package:
        name: "jdk-8u171-linux-x64.rpm"
        state: present
    - name: "Checking hadoop and installing"
      block:
        - name: "Checking hadoop"
          command: "rpm -q hadoop"
          changed_when: False
      rescue:
        - name: "Installing hadoop"
          command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
    - name: "Configuring Hadoop Datanode"
      template:
        src: "{{ item }}"
        dest: "/etc/hadoop"
      loop:
        - "hdfs-site.xml"
        - "core-site.xml"
      notify:
        - "Creating Datanode Directory"
        - "start hadoop"
    - name: Enable Firewall to port 9001
      firewalld:
        port: "9001/tcp"
        state: enabled
        permanent: yes
        immediate: yes
  handlers:
    - name: "Creating Datanode Directory"
      file:
        path: "{{ dir }}"
        state: "directory"
    - name: "start hadoop"
      command: "hadoop-daemon.sh start datanode"
